### ISSUE TITLE
Scene is solid color

### ISSUE THREAD

**Issue by NickDiMucci** [prime31/SpriteLightKit#2]
After setting up my cameras per the instructions in the README (and the demo scene), my camera just renders a solid pink color. 

Screen shot of scene and camera settings
![image](https://cloud.githubusercontent.com/assets/1623178/12093597/eed9f3be-b2d1-11e5-93b1-4f2b6e53037f.png)

![image](https://cloud.githubusercontent.com/assets/1623178/12093633/155fed2c-b2d2-11e5-87c4-28542e3436af.png)

I toggled a bunch of different options but not sure what's going on here.

**Comment by slonermike** [comment]
What do you see in the demo scene?

**Comment by NickDiMucci** [comment]
The demo scene works fine, as expected. I compared my scene with the demo scene and I couldn't see any discrepancies that would explain the issue.

**Comment by prime31** [comment]
Good old Unity pink almost always means a missing Material. Double check the Material on that sucker and make sure it's non-null.
